---
title: "Data Wrangling"
author: "Stephanie Cheng"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(janitor)
library(fastDummies)
library(broom)
```

```{r cleaning and loading data, echo=FALSE}

# To clean and load the data, I used read.csv to read the csv files. I then used
# clean_names() from the janitor package to make the column names easier to work
# with. Then I went through and renamed all the column names with appropriate
# variable names since the original names were in the form of questions that the
# questionnaire initially used (which are long and tedious to work with). I did
# this for both the 2017 and 2019 data, trying my best to be consistent across
# the data since the questionnaires for both years were slightly different.

census_2019_raw <- read.csv("./raw-data/design_census_2019.csv") %>%
  clean_names() %>%
  rename(career_duration = i_ve_worked_in_design_for,
         job_type = i_work_in,
         industry_type = industries_i_work_with,
         skills = my_skills_include,
         currently_learning = i_am_currently_learning,
         employment_status = i_am_currently_a_an,
         job_level = i_m_a_an,
         job_challenges = my_job_is_challenging_because,
         job_pros = my_job_is_great_because,
         org_size = my_organization_has,
         department_size = my_department_has,
         job_duration = i_ve_worked_here_for,
         role_duration = i_ve_had_my_role_for,
         work_hours = i_typically_work,
         salary = i_make,
         benefits = my_benefits_include,
         advancement_opportunities = i_have,
         learning_status = i_am,
         design_satisfaction_level = i_am_1,
         job_stability = i_feel,
         side_gigs = on_the_side_i,
         learned_design_from = i_learned_design_from,
         degree_subject = i_got_my_degree_in,
         number_of_jobs = i_ve_had,
         up_to_date_method = i_stay_current_with_design_by,
         job_satisfaction_level = i_m_currently,
         zip_code = my_zip_code_is,
         age = my_age_is,
         gender = i_identify_as,
         ethnicity = i_am_2,
         issues_in_design = i_feel_the_most_critical_issues_challenges_currently_facing_design_are,
         biggest_future_impact = i_think_the_emerging_future_technologies_that_will_have_the_biggest_impact_on_design_are,
         most_critical_skills = i_think_the_most_critical_design_skills_for_the_future_will_be,
         priorities = my_main_priorities_are) %>%
  select(age, gender, ethnicity, work_hours, salary, industry_type, design_satisfaction_level, job_type, skills, employment_status, org_size, department_size, job_stability, learned_design_from, career_duration) %>%
  mutate(census_year = 2019)

census_2017_raw <- read.csv("./raw-data/design_census_2017.csv") %>%
  clean_names() %>%
  rename(career_duration = starts_with("x1_"),
         job_type = starts_with("x2_"),
         skills = starts_with("x3_"),
         employment_status = starts_with("x4_"),
         company_type = starts_with("x5_"),
         org_size = starts_with("x9_"),
         department_size = starts_with("x10_"),
         industry_type = starts_with("x11_"),
         job_duration = starts_with("x12_"),
         job_level = starts_with("x13_"),
         role_duration = starts_with("x16_"),
         work_hours = starts_with("x17_"),
         salary = starts_with("x18_"),
         benefits = starts_with("x19_"),
         advancement_opportunities = starts_with("x20_"),
         learning_status = starts_with("x21_"),
         job_satisfaction_level = starts_with("x22_"),
         job_stability = starts_with("x23_"),
         side_gigs = starts_with("x24"),
         cups_of_coffee = starts_with("x25"),
         highest_education = starts_with("x26_"),
         learned_design_from = starts_with("x27_"),
         degree_subject = starts_with("x28_"),
         number_of_jobs = starts_with("x29_"),
         number_of_job_shifts = starts_with("x30_"),
         up_to_date_method = starts_with("x31_"),
         areas_of_improvement = starts_with("x33_"),
         job_status = starts_with("x34_"),
         zip_code = starts_with("x36_"),
         age = starts_with("x37_"),
         gender = starts_with("x38_"),
         lgbtqia_status = starts_with("x39_"),
         ethnicity = starts_with("x40_"),
         issues_in_design = starts_with("x41_"),
         biggest_future_impact = starts_with("x42_"),
         most_critical_skills = starts_with("x43_")) %>%
  select(age, gender, ethnicity, work_hours, salary, industry_type, job_satisfaction_level, job_type, skills, employment_status, org_size, department_size, job_stability, learned_design_from, career_duration)

us_zips <- read.csv("./raw-data/uszips.csv") %>%
  select(zip, state_name, state_id, lat, lng, city)

# Cleaning us company data by collapsing repetitive factors

us_companies <- read.csv("./raw-data/us_companies.csv")

fct_collapse(us_companies$company_category, `Data/Technology` = c("Data/Technology", "Data/Technology,"))
fct_collapse(us_companies$company_category, `Housing/Real Estate` = c("Housing/Real Estate", "Housing/Real Estate,"))
```

```{r cleaning, echo=FALSE}

# got rid of outlier salary data

census_2017_model <- census_2017_raw %>%
  filter(!salary > 1000000) %>%
  select(age, gender, career_duration, org_size, department_size, job_satisfaction_level, salary)

# figuring out the mean salary in each bracket based on 2017 data

avg_salary_8<- census_2017_model %>%
  filter(salary >= 200000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_7 <- census_2017_model %>%
  filter(salary >= 150000 & salary < 200000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_6 <- census_2017_model %>%
  filter(salary >= 100000 & salary < 150000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_5 <- census_2017_model %>%
  filter(salary >= 75000 & salary < 100000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_4 <- census_2017_model %>%
  filter(salary >= 50000 & salary < 75000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_3 <- census_2017_model %>%
  filter(salary >= 35000 & salary < 50000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_2 <- census_2017_model %>%
  filter(salary >= 25000 & salary < 35000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

avg_salary_1 <- census_2017_model %>%
  filter(salary < 25000) %>%
  summarize(avg_salary = mean(salary)) %>%
  round(digits = 0) %>%
  pull(avg_salary)

# assign actual salary values to 2019 data using a join

salary_join <- tibble(
  salary = c("$200,000+", "$150,000 to $199,999", "$100,000 to $149,999", "$75,000 to $99,999", "$50,000 to $74,999", "$35,000 to $49,999", "$25,000 to $34,999", "Less than $25,000"),
  salary_exact = c(avg_salary_8, avg_salary_7, avg_salary_6, avg_salary_5, avg_salary_4, avg_salary_3, avg_salary_2, avg_salary_1)
)

census_2019_model <- left_join(census_2019_raw, salary_join, by = "salary") %>%
  select(age, gender, career_duration, org_size, department_size, design_satisfaction_level, salary_exact) %>%
  mutate(job_satisfaction_level = design_satisfaction_level,
         salary = salary_exact) %>%
  select(-design_satisfaction_level, -salary_exact)

# assign satisfaction level to a number using a join (for both 2017 and 2019)

satisfaction_levels_2019 <- tibble(
  job_satisfaction_level = c("Not really satisfied, but I deal" , "Happy, but there's room for improvement", "Extremely satisfied with my work situation", "Ready to call it quits", "Not sure"),
  satisfaction_level = c(1, 2, 3, 0, NA)
)

satisfaction_levels_2017 <- tibble(
  job_satisfaction_level = c("Not great", "Pretty good", "The best", "The worst", "Not sure"),
  satisfaction_level = c(1, 2, 3, 0, NA)
)

census_2019_model <- left_join(census_2019_model, satisfaction_levels_2019, by = "job_satisfaction_level") %>%
  filter(job_satisfaction_level != "Not sure") %>%
  select(-job_satisfaction_level) %>%
  mutate(year = "2019")

census_2017_model <- left_join(census_2017_model, satisfaction_levels_2017, by = "job_satisfaction_level") %>%
  filter(job_satisfaction_level != "Not sure") %>%
  select(-job_satisfaction_level) %>%
  mutate(year = "2017")

# joining both 2017 and 2019 cleaned data

census_model_joined <- rbind(census_2019_model, census_2017_model) %>%
  mutate(gender = map_chr(gender, ~ifelse(. == "Female", "Female", 
                                      ifelse(. == "Male", "Male", "Other"))),
         career_duration = str_replace_all(career_duration, " ", ""),
         org_size = str_replace_all(org_size, " ", ""),
         org_size = map_chr(org_size, ~ifelse(. == "501-1,000employees", "501-1000employees", .)),
         org_size = map_chr(org_size, ~ifelse(. == "1,000+employees", "1000+employees", .)),
         org_size = map_chr(org_size, ~ifelse(. == "Notsure", "Unsure", .)),
         department_size = str_replace_all(department_size, " ", ""),
         department_size = map_chr(department_size, ~ifelse(. == "21+people", "20+people", .))) %>%
  filter(age < 150) %>%
  filter(age > 5) %>%
  mutate(age_group = case_when(age < 21 ~ "<21",
                               age > 20 & age <= 25 ~ "21-25",
                               age > 25 & age <= 30 ~ "26-30",
                               age > 30 & age <= 35 ~ "31-35",
                               age > 35 & age <= 40 ~ "36-40",
                               age > 40 & age <= 45 ~ "41-45",
                               age > 45 & age <= 50 ~ "46-50",
                               age > 50 & age <= 60 ~ "51-60",
                               age > 60 ~ "60+"))

# releveling factors

census_model_joined$career_duration <- factor(census_model_joined$career_duration,
                                              levels = c("Lessthan1year", "1-4years", "5-9years", "10-14years", "15-20years", "20+years"))

levels(census_model_joined$career_duration) <- c("Less than 1 year", "1-4 years", "5-9 years", "10-14 years", "15-20 years", "20+ years")

census_model_joined$org_size <- factor(census_model_joined$org_size,
                                              levels = c("1-10employees", "11-50employees", "51-100employees", "101-250employees", "251-500employees", "501-1000employees", "1000+employees", ""))

levels(census_model_joined$org_size) <- c("1-10 employees", "11-50 employees", "51-100 employees", "101-250 employees", "251-500 employees", "501-1000 employees", "1000+ employees", "")

census_model_joined$department_size <- factor(census_model_joined$department_size,
                                              levels = c("Justme", "2-4people", "5-10people", "11-20people", "20+people", ""))

levels(census_model_joined$department_size) <- c("Just Me", "2-4 people", "5-10 people", "11-20 people", "20+ people", "")

write_rds(census_model_joined,"./design_project/census_model_joined.rds")

```


```{r tab 1, echo=FALSE}

# Tab 1 : Who are our designers?

# Graph for age

census_2017 %>%
  group_by(age) %>%
  count() %>%
  ggplot(aes(x = age, y = n)) +
  geom_bar(stat = "identity", fill = "#4fe3bc") +
  theme_minimal() +
  labs(x = "Age",
       y = "Number of Designers",
       title = "Distribution of Designers by Age",
       subtitle = "From 2017 Design Census")

# Graph for gender

gender_colors <- c("#eb6a90", "#6ab5eb", "#d081f0", "#4f32ad", "#8d7feb")
census_2017 %>%
  group_by(gender) %>%
  count() %>%
  mutate(prop = round(n/nrow(census_2017)*100, digits = 1),
         prop2 = map(prop, ~ifelse(prop < 2, "", paste(as.character(.), "%", sep = "")))) %>%
  ggplot(aes(x = 2, y = n, fill = gender)) +
  geom_bar(stat = "identity", color = "white") +
  geom_text(aes(label = prop2, x = 2.7), position = position_stack(vjust = 0.5), size = 3) +
  coord_polar(theta = "y", start = 0) +
  scale_fill_manual(values = gender_colors, name = "Gender") +
  theme_void() +
  xlim(0.5, 2.7) +
  labs(title = "Designers by Gender",
       subtitle = "From 2017 Design Census")

# Graph for employment status

census_2017 %>%
  group_by(employment_status) %>%
  count() %>%
  mutate(prop = round(n/nrow(census_2017)*100, digits = 1),
         prop2 = map(prop, ~ifelse(prop < 2, "", paste(as.character(.), "%", sep = "")))) %>%
  ggplot(aes(x = 2, y = n, fill = employment_status)) +
  geom_bar(stat = "identity", color = "white") +
  geom_text(aes(label = prop2, x = 2.7), position = position_stack(vjust = 0.5), size = 3) +
  coord_polar(theta = "y", start = 0) +
    theme_void() +
  xlim(0.5, 2.7) +
  labs(title = "Designers by Employment Status",
       subtitle = "From 2017 Design Census")
```

```{r regresson}

# Salary predictor

model_salary <- lm(salary ~ age + gender + career_duration + org_size + department_size , data = census_model_joined)

model_salary %>%
  tidy()

prediction_salary <- predict(model_salary, tibble(age = 22, 
                             gender = "Female", 
                             career_duration = "Less than 1 year", 
                             org_size = "11-50 employees", 
                             department_size = "Just Me"),
        interval = "confidence") %>%
  as_data_frame()


ggplot() +
  scale_x_continuous(name = "x") +
  scale_y_continuous(name = "y") +
  geom_rect(data = prediction_salary, aes(xmin = prediction_salary[1] %>% pull(), 
                                          xmax = prediction_salary[3] %>% pull(), 
                                          ymin = 0, 
                                          ymax = 1))


```

```{r satisfaction predictior}
# Job Satisfaction predictor


model_satisfaction <- lm(satisfaction_level ~ age + gender + career_duration + org_size + department_size + salary, data = census_model_joined)

model_satisfaction%>%
  tidy()

predict(model_satisfaction, tibble(age = 22, 
                             gender = "Female", 
                             career_duration = "1-4years", 
                             org_size = "11-50employees", 
                             department_size = "Justme", 
                             salary = 55000),
        interval = "confidence")

write_rds(model_salary,"./design_project/model_salary.rds")
```


```{r tab 2 graphs, echo=FALSE}
bar_palette <- c('#6981e6', '#6f8ce6', '#7597e7', '#7aa2e7', '#7eade7', '#82b9e7', '#86c4e7', '#89cfe7', '#8cdbe6')

census_model_joined %>%
  filter(year == 2017) %>%
  group_by(age_group) %>%
  summarize(mean_salary = mean(salary)) %>%
  ggplot(aes(age_group, mean_salary)) +
  geom_col(aes(fill = age_group)) +
  scale_fill_manual(values = bar_palette, name = "Age ") +
  theme_classic() +
  labs(x = "Age Group",
       y = "Mean Salary",
       title = "Salary by Age",
       subtitle = "Of Designers in the US")



census_model_joined %>%
  filter(year == 2017) %>%
  group_by(career_duration) %>%
  summarize(mean_satisfaction = mean(satisfaction_level)) %>%
  ggplot(aes(career_duration, mean_satisfaction)) +
  geom_col(aes(fill = career_duration)) +
  scale_fill_manual(values = bar_palette, name = "Age ") +
  theme_classic()


```
 
